---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - store.mylab.local
  resources:
  - bookstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - store.mylab.local
  resources:
  - bookstores/finalizers
  verbs:
  - update
- apiGroups:
  - store.mylab.local
  resources:
  - bookstores/status
  verbs:
  - get
  - patch
  - update
