apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bookstore-operator.fullname" . }}-manager-role
  labels:
    {{- include "bookstore-operator.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: [services]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [apps]
  resources: [deployments]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [store.mylab.local]
  resources: [bookstores]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [store.mylab.local]
  resources: [bookstores/finalizers]
  verbs: [update]
- apiGroups: [store.mylab.local]
  resources: [bookstores/status]
  verbs: [get, patch, update]
